
// This file has been generated by the GUI designer. Do not modify.
namespace JiraAssistant.Mono
{
	public partial class ContentDisplayWidget
	{
		private global::Gtk.UIManager UIManager;

		private global::Gtk.Action JIRAAction;

		private global::Gtk.Action LogoutAction;

		private global::Gtk.Table table1;

		private global::Gtk.MenuBar mainMenu;

		private global::Gtk.Notebook notebook;

		private global::JiraAssistant.Mono.JiraServerInfoWidget jiraserverinfowidget1;

		private global::Gtk.Label label2;

		private global::JiraAssistant.Mono.ToolsWidget toolswidget1;

		private global::Gtk.Label label3;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget JiraAssistant.Mono.ContentDisplayWidget
			Stetic.BinContainer w1 = global::Stetic.BinContainer.Attach(this);
			this.UIManager = new global::Gtk.UIManager();
			global::Gtk.ActionGroup w2 = new global::Gtk.ActionGroup("Default");
			this.JIRAAction = new global::Gtk.Action("JIRAAction", global::Mono.Unix.Catalog.GetString("JIRA"), null, null);
			this.JIRAAction.ShortLabel = global::Mono.Unix.Catalog.GetString("JIRA");
			w2.Add(this.JIRAAction, null);
			this.LogoutAction = new global::Gtk.Action("LogoutAction", global::Mono.Unix.Catalog.GetString("Logout"), null, null);
			this.LogoutAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Logout");
			w2.Add(this.LogoutAction, null);
			this.UIManager.InsertActionGroup(w2, 0);
			this.Name = "JiraAssistant.Mono.ContentDisplayWidget";
			// Container child JiraAssistant.Mono.ContentDisplayWidget.Gtk.Container+ContainerChild
			this.table1 = new global::Gtk.Table(((uint)(2)), ((uint)(1)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.UIManager.AddUiFromString("<ui><menubar name=\'mainMenu\'><menu><menuitem/></menu></menubar></ui>");
			this.mainMenu = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/mainMenu")));
			this.mainMenu.Name = "mainMenu";
			this.table1.Add(this.mainMenu);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1[this.mainMenu]));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.notebook = new global::Gtk.Notebook();
			this.notebook.CanFocus = true;
			this.notebook.Name = "notebook";
			this.notebook.CurrentPage = 1;
			// Container child notebook.Gtk.Notebook+NotebookChild
			this.jiraserverinfowidget1 = new global::JiraAssistant.Mono.JiraServerInfoWidget();
			this.jiraserverinfowidget1.Events = ((global::Gdk.EventMask)(256));
			this.jiraserverinfowidget1.Name = "jiraserverinfowidget1";
			this.notebook.Add(this.jiraserverinfowidget1);
			// Notebook tab
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("JIRA Connection");
			this.notebook.SetTabLabel(this.jiraserverinfowidget1, this.label2);
			this.label2.ShowAll();
			// Container child notebook.Gtk.Notebook+NotebookChild
			this.toolswidget1 = new global::JiraAssistant.Mono.ToolsWidget();
			this.toolswidget1.Events = ((global::Gdk.EventMask)(256));
			this.toolswidget1.Name = "toolswidget1";
			this.notebook.Add(this.toolswidget1);
			global::Gtk.Notebook.NotebookChild w5 = ((global::Gtk.Notebook.NotebookChild)(this.notebook[this.toolswidget1]));
			w5.Position = 1;
			// Notebook tab
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Tools");
			this.notebook.SetTabLabel(this.toolswidget1, this.label3);
			this.label3.ShowAll();
			this.table1.Add(this.notebook);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1[this.notebook]));
			w6.TopAttach = ((uint)(1));
			w6.BottomAttach = ((uint)(2));
			this.Add(this.table1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			w1.SetUiManager(UIManager);
			this.Hide();
		}
	}
}
