
// This file has been generated by the GUI designer. Do not modify.
namespace JiraAssistant.Mono
{
	public partial class StatusBarWidget
	{
		private global::Gtk.Statusbar statusbar4;

		private global::Gtk.Label connectionStatus;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget JiraAssistant.Mono.StatusBarWidget
			global::Stetic.BinContainer.Attach(this);
			this.Name = "JiraAssistant.Mono.StatusBarWidget";
			// Container child JiraAssistant.Mono.StatusBarWidget.Gtk.Container+ContainerChild
			this.statusbar4 = new global::Gtk.Statusbar();
			this.statusbar4.Name = "statusbar4";
			this.statusbar4.Spacing = 6;
			// Container child statusbar4.Gtk.Box+BoxChild
			this.connectionStatus = new global::Gtk.Label();
			this.connectionStatus.Name = "connectionStatus";
			this.connectionStatus.LabelProp = global::Mono.Unix.Catalog.GetString("Offline");
			this.statusbar4.Add(this.connectionStatus);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.statusbar4[this.connectionStatus]));
			w1.Position = 1;
			w1.Expand = false;
			w1.Fill = false;
			this.Add(this.statusbar4);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
