
// This file has been generated by the GUI designer. Do not modify.
namespace JiraAssistant.Mono.Windows
{
	public partial class TextPreviewDialog
	{
		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TextView textView;

		private global::Gtk.Button saveAsButton;

		private global::Gtk.Button buttonOk;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget JiraAssistant.Mono.Windows.TextPreviewDialog
			this.Name = "JiraAssistant.Mono.Windows.TextPreviewDialog";
			this.Title = global::Mono.Unix.Catalog.GetString("Preview window");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child JiraAssistant.Mono.Windows.TextPreviewDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.textView = new global::Gtk.TextView();
			this.textView.CanFocus = true;
			this.textView.Name = "textView";
			this.textView.Editable = false;
			this.GtkScrolledWindow.Add(this.textView);
			w1.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(w1[this.GtkScrolledWindow]));
			w3.Position = 0;
			// Internal child JiraAssistant.Mono.Windows.TextPreviewDialog.ActionArea
			global::Gtk.HButtonBox w4 = this.ActionArea;
			w4.Name = "dialog1_ActionArea";
			w4.Spacing = 10;
			w4.BorderWidth = ((uint)(5));
			w4.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.saveAsButton = new global::Gtk.Button();
			this.saveAsButton.CanFocus = true;
			this.saveAsButton.Name = "saveAsButton";
			this.saveAsButton.UseUnderline = true;
			this.saveAsButton.Label = global::Mono.Unix.Catalog.GetString("Save as ...");
			this.AddActionWidget(this.saveAsButton, 0);
			global::Gtk.ButtonBox.ButtonBoxChild w5 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w4[this.saveAsButton]));
			w5.Expand = false;
			w5.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget(this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w6 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w4[this.buttonOk]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 689;
			this.DefaultHeight = 474;
			this.Show();
		}
	}
}
