
// This file has been generated by the GUI designer. Do not modify.
namespace JiraAssistant.Mono.Widgets.ToolsWidgets.ParametersWidgets
{
	public partial class DateParameterWidget
	{
		private global::Gtk.Calendar calendar;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget JiraAssistant.Mono.Widgets.ToolsWidgets.ParametersWidgets.DateParameterWidget
			global::Stetic.BinContainer.Attach(this);
			this.Name = "JiraAssistant.Mono.Widgets.ToolsWidgets.ParametersWidgets.DateParameterWidget";
			// Container child JiraAssistant.Mono.Widgets.ToolsWidgets.ParametersWidgets.DateParameterWidget.Gtk.Container+ContainerChild
			this.calendar = new global::Gtk.Calendar();
			this.calendar.CanFocus = true;
			this.calendar.Name = "calendar";
			this.calendar.DisplayOptions = ((global::Gtk.CalendarDisplayOptions)(35));
			this.Add(this.calendar);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
