
// This file has been generated by the GUI designer. Do not modify.
namespace JiraAssistant.Mono.Widgets.ToolsWidgets
{
	public partial class JqlBasedToolWidget
	{
		private global::Gtk.Table table2;

		private global::Gtk.Label label2;

		private global::Gtk.Table table1;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget JiraAssistant.Mono.Widgets.ToolsWidgets.JqlBasedToolWidget
			global::Stetic.BinContainer.Attach(this);
			this.HeightRequest = 300;
			this.Name = "JiraAssistant.Mono.Widgets.ToolsWidgets.JqlBasedToolWidget";
			// Container child JiraAssistant.Mono.Widgets.ToolsWidgets.JqlBasedToolWidget.Gtk.Container+ContainerChild
			this.table2 = new global::Gtk.Table(((uint)(2)), ((uint)(1)), false);
			this.table2.Name = "table2";
			this.table2.RowSpacing = ((uint)(6));
			this.table2.ColumnSpacing = ((uint)(6));
			// Container child table2.Gtk.Table+TableChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.Ypad = 10;
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Parameters");
			this.table2.Add(this.label2);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table2[this.label2]));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.table1 = new global::Gtk.Table(((uint)(1)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			this.table2.Add(this.table1);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table2[this.table1]));
			w2.TopAttach = ((uint)(1));
			w2.BottomAttach = ((uint)(2));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			this.Add(this.table2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Show();
		}
	}
}
