
// This file has been generated by the GUI designer. Do not modify.
namespace JiraAssistant.Mono
{
	public partial class JiraServerInfoWidget
	{
		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget JiraAssistant.Mono.JiraServerInfoWidget
			global::Stetic.BinContainer.Attach(this);
			this.Name = "JiraAssistant.Mono.JiraServerInfoWidget";
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
