
// This file has been generated by the GUI designer. Do not modify.
namespace JiraAssistant.Mono
{
	public partial class ToolsWidget
	{
		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget JiraAssistant.Mono.ToolsWidget
			global::Stetic.BinContainer.Attach(this);
			this.Name = "JiraAssistant.Mono.ToolsWidget";
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
